/*
	The config file for the plugin
 */
const { registerBlockType } = wp.blocks
/*
* To use translation in admin
* const { __ } = wp.i18n
* */

registerBlockType('info-bulle-block/info-bulle-block', {
	/* The plugin title in the admin */
	title: "Admin title",
	category: "widgets",
	/* What the plugin supports */
	supports: {
		html: false
	},
	/* Specify what html code will be generated in the admin
	* className var is automatically generated by Wordpress
	*/
	edit ({ className }) {
		return <div className={ className }>Bonjour</div>
	},

	/* Specify what html code will be generated in front end
	* if we want to make a dynamic block, leave the return to null
	*/
	save () {
		return null
	}
})